version: "3.9"

services:

  database:
    build: database
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_PASSWORD: user-secret

  es: 
    image: elasticsearch

  nb-puller:
    build: ./nb-puller
    volumes:
      - ./nb-puller:/app
    environment:
      GIT_KEY_LOCATION: /git-keys/id_ed25519
    secrets:
      - source: git_ssh_keys
        target: /git-keys
        mode: 0400

  nb-server:
    build: ./nb-server
    volumes:
      - ./nb-server/nginx.conf:/etc/nginx/nginx.conf

  js-app:
    build: ./js-app
    environment:
      MARIADB_PASSWORD: user-secret
    volumes:
      - ./js-app:/js-app
    depends_on:
      - database

  runner:
    build: ./runner

  load-balancer:
    build: ./load-balancer
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - js-app
      - nb-serve

secrets:
  git_ssh_keys:
    file: ~/.ssh/personal/git
