version: "3.9"

services:

  database:
    build: database
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: true
      MARIADB_PASSWORD: user-secret

  cache:
    image: redis

  js-app:
    build: ./js-app
    environment:
      MARIADB_PASSWORD: user-secret
    volumes:
      - ./js-app:/js-app
    depends_on:
      - jobs
      - cache
      - database

  run-archive:
    image: redis

  runner:
    build: ./runner
  
  load-balancer:
    build: ./load-balancer
    ports:
      - 80:80
    depends_on:
      - nb-mill-client
